version: '3.0.0'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/data/postgres
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh

volumes:
  postgres_data:
